### ISSUE TITLE
Zip directory structure out of sync with documentation 

### ISSUE THREAD

**Issue by RichardDavies** [PomDev2/wlanpoke#1]
Thank you so much for your continued work on this script! I've been using a previous version with great success.

I noticed that in the wlanpoke.0.7.0.zip file, all files are now inside a wlanpoke-0.7.0 directory. However, the instructions in the manual.txt for unzipping it still assume that the files will be placed in /etc/wlanpoke, but they end up in /etc/wlanpoke/wlanpoke-0.7.0. Obviously not a huge deal, but something that will potentially trip up an inexperienced user simply trying to follow the directions.

**Comment by PomDev2** [comment]
So true. An updated 'manual.txt' 0.7.0.1 now includes new instructions for handling zip files with the contents in a versioned project directory. Download it from the main branch. These new instructions need to be tested. Thanks for the report.

**Comment by RichardDavies** [comment]
Thank you! Those updated instructions worked for me.
