### ISSUE TITLE
Webserver keeps crashing after one or two hours

### ISSUE THREAD

**Issue by PomDev2** [PomDev2/wlanpoke#4]
From [forum post](https://forums.slimdevices.com/showthread.php?111663-Community-Build-Radio-Firmware&p=1019544&viewfull=1#post1019544)
For now it works for >95% and that is a lot more then i had. So thanks for that already.
The webserver keeps crashing after one or two hours.
You suggested some lines added to a script. Please explain a bit more in detail (pref a example) to find the cause.

**Comment by PomDev2** [comment]
The 'web' server uses three processes at all times. The man process runs ahttpd.sh, which creates a named pipe to send results to nc. nc is piped (via an unnamed pipe) to arequest.sh to handle incoming requests from a client (e.g., Firefox). 
`    cat $WLPIPENAME | nc -lp $TCPPORT | ./arequest.sh`
arequest.sh simply calls awstats.sh to actually get the requested information, which arequest then returns to the client by writing to the named pipe, which cat then writes to nc, etc.
`    ./awstats.sh > $WLPIPENAME`

You can see the 3 processes on the web page when it is working, or via ssh, along with two other processes called by awstats.sh that are supplying the process data.

This scheme has failed twice here on 7 radios. The process list (ps alxw ) shows only the cat process still running. nc and the arequest.sh scripts have disappeared. This is likely because of a failure in nc or in the script. nc might fail if the caller (or network) has disappeared (or perhaps not) before it can return results. The script might stop due to some fatal error, such as a math error.

To troubleshoot this, you can add echo statements like the following suggestions to see where the arequest or awstats scripts fail, e.g., in arequest.sh
`   echo "before awstats.sh" >> /var/log/w.log`
`    ./awstats.sh > $WLPIPENAME     `
`    echo "after awstats.sh" >> /var/log/w.log  `
to awstats.sh, add:
`  trq=`echo ${REQUEST##/}`        # get rid of root '/' `
`  echo awstats: $CmdLine $HOSTNAME $trq  >> /var/log/w.log  `
then
`  echo awstats: done `
at the end of the file

When the server fails, examine the /var/log/w.log file, and see what the last entry was. Something just after that entry went wrong. Add yet more echo statements until you have pinpointed the problematic statement, and restart the web server:
`  cd /etc/wlanpoke/ahttpd.sh -F -W 8080   `    or so

You may want to add timestamps to the log file, e.g., 
`  echo $(date -Isec) awstats: done `
is fairly simple. These are just suggestions, they have not been tested.

Good luck. It may be that it is not possible to trace this. In that case, some code to test for nc or arequest.sh running could be added, and to relaunch them if not, but this is getting complicated for a 'simple' server.

**Comment by PomDev2** [comment]
Oops, `cd /etc/wlanpoke/ahttpd.sh -F -W 8080` should be
```
cd /etc/wlanpoke/
./ahttpd.sh -F -p 8080

```

**Comment by PomDev2** [comment]
From forum [post](https://forums.slimdevices.com/showthread.php?111663-Community-Build-Radio-Firmware&p=1019593&viewfull=1#post1019593)
> But i am very unsure about the locations of the echo arguments in the files. especially: in arequest.sh
> So a complete example file would be nice. I use the standard wlanpoke files. 

Here are two examples, untested:

[awstuffDB.zip](https://github.com/PomDev2/wlanpoke/files/6340088/awstuffDB.zip)

Rename to save the original files, remove the DB suffix from these files, place them in the /etc/wlanpoke folder, then

` cd /etc/wlanpoke/ `
` ./ahttpd.sh -F -p 8080`

and examine /var/log/w.log after the server stops working.

**Comment by seth-space** [comment]
changed the permissions to 0755
Webserver crashed and took the radio network with it.
With these two files the radio keeps losing connection.
Will try to put the old ones back.

for now i will run without the webserver. If there are options to test it without loosing connection i will try.

**Comment by PomDev2** [comment]
Did you ever look into w.log to see what might be crashing your web server? Sorry, I didn't see this sooner. This issue is now stale. Please open another issue if you want to work on this more.
